# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version=1.0.0
maven_group=com.thedeathlycow.moregeodes
archives_name=geodes
enabled_platforms=fabric,neoforge,quilt

# Minecraft properties
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3

# Dependencies
# Fabric
fabric_loader_version=0.16.2
fabric_api_version=0.102.1+1.21.1
fabric_kotlin_version=1.12.0+kotlin.2.0.10

# NeoForge
neoforge_version=21.1.21
forgified_fabric_api_version=0.102.0+2.0.12+1.21.1
kotlin_for_forge_version=5.4.0
yarn_mappings_patch_neoforge_version=1.21+build.4

# Quilt
quilt_loader_version=0.26.4-beta.1
quilted_fabric_api_version=11.0.0-alpha.3+0.102.0-1.21
